scalar Upload

type UploadFile {
  filename: String!
  label: String!
  type: String!
  mimetype: String!
  encoding: String!
  size: Int!
  extension: String!
}

input FileDetails {
  label: String
  type: String
}

type Mutation {
  uploadFile(file: Upload!, details: FileDetails): UploadFile!
}
